#---------------------------------#
#           environment           #
#---------------------------------#
image: Visual Studio 2017

install:
  - ps: |
      $logo = (Invoke-WebRequest "https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.raw").toString()
      Write-Host "$logo" -ForegroundColor Green
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
  - cmd: dir


#---------------------------------#
#              build              #
#---------------------------------#
build_script:
  - cmd: PowerShell -Version 2.0 .\build.ps1


#---------------------------------#
#              tests              #
#---------------------------------#
test:
  assemblies: '**\*.Test.dll'
  categories:
    except:
      - Manual


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: '*.nupkg'
    name: NuGet


#---------------------------------#
#            on finish            #
#---------------------------------#
on_finish:
  - ps: Get-ChildItem -Path Failed_*.png -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

#---------------------------------#
#              deploy             #
#---------------------------------#
deploy:
  provider: NuGet
  api_key:
    secure: +Bilz7dCD+2p0lK1ZouppJTQoLELbF0WvTPhwT56qD6NCJAfJnlWEe8Ig5igR34O
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
